// ============================================================
// DATA LAYER — Edit content here without touching UI code
// ============================================================

// 27 AI-era value delivery models
const MODELS = [
  {id:1,name:"We Advise on Strategy",subtitle:"Traditional Mgmt Consultancy",examples:"McKinsey, BCG, Bain",x:10,y:85,status:"legacy",iface:"human",pricing:"project",archetype:"Sage",problems:["revenue","efficiency","capability"],description:"Senior humans embed deeply, diagnose problems, recommend solutions. AI is democratizing the insight they sell.",bestFor:"Ambiguous strategic problems where the client can't articulate what's wrong"},
  {id:2,name:"We Do Your Repetitive Work Cheaper",subtitle:"Traditional BPO",examples:"Infosys, Wipro, Cognizant",x:12,y:45,status:"legacy",iface:"human",pricing:"retainer",archetype:"Servant",problems:["efficiency"],description:"Offshore humans handle back-office at lower cost. AI eliminates the labor arbitrage entirely.",bestFor:"High-volume repetitive ops — but AI does this cheaper now"},
  {id:3,name:"Here's a Tool, You Figure It Out",subtitle:"Classic Horizontal SaaS",examples:"Salesforce, HubSpot, Workday",x:65,y:15,status:"legacy",iface:"gui",pricing:"subscription",archetype:"Ruler",problems:["revenue","efficiency"],description:"One-size-fits-all software. Customer adapts to the tool. The 'hammer' model.",bestFor:"Standardizable workflows where process conformity is acceptable"},
  {id:4,name:"We Build Custom Software & Hand It Over",subtitle:"Dev Shop / System Integrator",examples:"Accenture, Deloitte Digital",x:15,y:55,status:"legacy",iface:"human",pricing:"project",archetype:"Builder",problems:["capability","efficiency"],description:"Custom software built by humans, scoped through relationships, delivered as a project.",bestFor:"Complex integrations — shrinking window"},
  {id:5,name:"Your Existing Tool, Now With AI Assist",subtitle:"AI-Augmented SaaS",examples:"Notion AI, Grammarly, HubSpot AI",x:72,y:20,status:"current",iface:"gui",pricing:"subscription",archetype:"Magician",problems:["efficiency","revenue"],description:"Same SaaS with AI bolted on. Still a tool — AI assists but you do the work.",bestFor:"Incremental productivity within existing workflows"},
  {id:6,name:"AI-Powered Workflow Tools You Operate",subtitle:"AI-Native Workflow SaaS",examples:"Clay, Apollo AI, Zapier AI",x:78,y:25,status:"current",iface:"gui",pricing:"subscription",archetype:"Creator",problems:["revenue","efficiency"],description:"Built AI-first. More capable but still delivers tools not outcomes.",bestFor:"Tech-savvy users who want control"},
  {id:7,name:"We Know Your Industry's Data Inside Out",subtitle:"Vertical Data Consultancy",examples:"Ascend Analytics, health data firms",x:30,y:70,status:"current",iface:"human",pricing:"project",archetype:"Sage",problems:["efficiency","revenue"],description:"Deep domain + data expertise via human relationships. Builds tools/pipelines and hands over.",bestFor:"Regulated verticals with messy, fragmented data"},
  {id:8,name:"We'll Get You Set Up With AI",subtitle:"Horizontal AI Implementation",examples:"Brainforge, generic AI consultancies",x:35,y:50,status:"current",iface:"human",pricing:"project",archetype:"Guide",problems:["capability","efficiency"],description:"Build AI systems, hand them over. Most crowded, least defensible.",bestFor:"Enterprises under board pressure to 'do AI'"},
  {id:9,name:"We Grow Your Revenue, AI Does the Work",subtitle:"AI-First Agency (Revenue)",examples:"AI outbound, AI creative agencies",x:55,y:65,status:"emerging",iface:"human",pricing:"retainer",archetype:"Hero",problems:["revenue"],description:"Human interface, AI delivery for growth. Real margin expansion.",bestFor:"Revenue work where ambiguity is high"},
  {id:10,name:"We Run Your Operations, AI Does the Work",subtitle:"AI-First Agency (Efficiency)",examples:"Pilot, AI ops firms",x:55,y:58,status:"emerging",iface:"human",pricing:"retainer",archetype:"Hero",problems:["efficiency"],description:"Human interface, AI delivery for ops. Strong automation path.",bestFor:"Back-office with measurable outcomes"},
  {id:11,name:"We Build Custom Software Faster With AI",subtitle:"AI-Augmented Bespoke Dev",examples:"Dev shops using Cursor/Copilot",x:42,y:55,status:"emerging",iface:"human",pricing:"project",archetype:"Builder",problems:["capability"],description:"Traditional dev shop with 3x AI acceleration. Temporary advantage.",bestFor:"Complex custom builds — window closing"},
  {id:12,name:"AI Runs Your Domain Ops Autonomously",subtitle:"Vertical AI Ops",examples:"AceDev (cloud ops)",x:80,y:40,status:"emerging",iface:"gui",pricing:"subscription",archetype:"Magician",problems:["efficiency"],description:"Domain-specific autonomous operations. Strong feedback loops.",bestFor:"Structured ops with clear success metrics"},
  {id:13,name:"Software Does the Efficiency Work For You",subtitle:"Service-as-Software (Efficiency)",examples:"Harvey, EvenUp, Klarna AI",x:88,y:35,status:"frontier",iface:"gui",pricing:"outcome",archetype:"Magician",problems:["efficiency"],description:"Self-serve, AI-delivered efficiency outcomes. The promised land.",bestFor:"High-volume structured work with clear outputs"},
  {id:14,name:"Software Grows Your Revenue For You",subtitle:"Service-as-Software (Revenue)",examples:"Barely exists",x:88,y:45,status:"frontier",iface:"gui",pricing:"outcome",archetype:"Magician",problems:["revenue"],description:"Hardest frontier. Revenue work is too ambiguous for most.",bestFor:"Only where inputs/outputs are highly structured"},
  {id:15,name:"Deeply Personalized Outcomes at Scale",subtitle:"Contextual Outcome Engine (CAS)",examples:"The convergence — no pure example",x:75,y:75,status:"frontier",iface:"hybrid",pricing:"outcome",archetype:"Oracle",problems:["revenue","efficiency","capability"],description:"The endgame. Bespoke experience at near-zero marginal cost.",bestFor:"Any problem where customization was too expensive"},
  {id:16,name:"We Maintain Your Orientation Fabric",subtitle:"Continuous Context Broker",examples:"Palantir-adjacent",x:45,y:90,status:"frontier",iface:"hybrid",pricing:"subscription",archetype:"Oracle",problems:["capability","revenue","efficiency"],description:"Builds the context layer that makes everything else work.",bestFor:"Orgs with degraded context across decision boundaries"},
  {id:17,name:"Routes Problems to Right AI+Human Blend",subtitle:"Outcome Marketplace / Router",examples:"No named example",x:70,y:55,status:"frontier",iface:"gui",pricing:"outcome",archetype:"Magician",problems:["revenue","efficiency","capability"],description:"Routes to optimal blend of AI agents + human experts dynamically.",bestFor:"Variable-complexity problems"},
  {id:18,name:"Independent Experts Sharing AI Infra",subtitle:"AI-Native Cooperative / Guild",examples:"Early signals in legal, accounting",x:40,y:75,status:"frontier",iface:"human",pricing:"retainer",archetype:"Sage",problems:["revenue","efficiency","capability"],description:"Domain experts share AI platform. Collective data makes everyone better.",bestFor:"Professional services where individual expertise matters"},
  {id:19,name:"Invisible AI Layer Inside Other Products",subtitle:"Embedded Intelligence (B2B2B)",examples:"White-label AI — early",x:85,y:30,status:"frontier",iface:"none",pricing:"outcome",archetype:"Invisible",problems:["efficiency","capability"],description:"Embeds inside other products. End customer never knows you exist.",bestFor:"Enabling platforms to offer AI outcomes"},
  {id:20,name:"We ARE Your Entire Business Function",subtitle:"Autonomous BU-as-a-Service",examples:"Rippling (aspiring), Pilot",x:72,y:68,status:"frontier",iface:"hybrid",pricing:"retainer",archetype:"Hero",problems:["efficiency","capability"],description:"Not a tool, not a task — the entire function as a managed service.",bestFor:"SMBs that need a full function but can't build the team"},
  {id:21,name:"AI Finds Opportunities, Humans Execute",subtitle:"Predictive Venture Builder",examples:"Demand radar concept",x:60,y:82,status:"frontier",iface:"hybrid",pricing:"outcome",archetype:"Explorer",problems:["revenue","capability"],description:"AI scans demand, validates, humans execute. Meta-OODA loop.",bestFor:"Speed of opportunity validation is the edge"},
  {id:22,name:"Deliberately Human, Deliberately Premium",subtitle:"Human Premium / Artisanal",examples:"Luxury advisory, concierge",x:5,y:95,status:"frontier",iface:"human",pricing:"project",archetype:"Sage",problems:["revenue","capability"],description:"Contrarian. Human-crafted becomes luxury as AI becomes ubiquitous.",bestFor:"High-trust work where 'a human did this' IS the value"},
  {id:23,name:"Software Guides You Through Doing It Yourself",subtitle:"Guided Self-Service",examples:"TurboTax, LegalZoom, Wix",x:50,y:20,status:"current",iface:"gui",pricing:"subscription",archetype:"Guide",problems:["efficiency","capability"],description:"Structures your labor, doesn't replace it. AI kills this first.",bestFor:"Complex tasks where judgment was hard to automate — falling fast"},
  {id:24,name:"Industry-Specific Platform You Adapt To",subtitle:"Vertical SaaS",examples:"Toast, Procore, Veeva",x:58,y:30,status:"current",iface:"gui",pricing:"subscription",archetype:"Ruler",problems:["efficiency","revenue"],description:"Deep domain logic in software. Stronger moat than horizontal SaaS.",bestFor:"Industry workflows where domain context is non-negotiable"},
  {id:25,name:"Build Your Business On Our Platform",subtitle:"Platform / Ecosystem",examples:"Shopify, Stripe, Webflow",x:62,y:22,status:"current",iface:"gui",pricing:"subscription",archetype:"Creator",problems:["revenue","capability"],description:"You build on their infra. AI transforms these — platforms do what you did manually.",bestFor:"Businesses needing infrastructure to build on"},
  {id:26,name:"We Sell Proprietary Data & Intelligence",subtitle:"Data / Intelligence-as-a-Service",examples:"ZoomInfo, Bloomberg, PitchBook",x:55,y:35,status:"current",iface:"gui",pricing:"subscription",archetype:"Oracle",problems:["revenue","efficiency","capability"],description:"Proprietary data access. Closest to Context Broker frontier.",bestFor:"Decisions requiring info not available publicly"},
  {id:27,name:"Raw AI Capability Via API",subtitle:"AI Model / API Provider",examples:"OpenAI, Anthropic, Cohere",x:92,y:10,status:"current",iface:"gui",pricing:"subscription",archetype:"Magician",problems:["capability"],description:"Pure capability, zero context. Enables everything else. Commoditizing.",bestFor:"Technical teams needing raw model capability"}
];

// 24 migration paths with action plans
const MIGRATIONS = [
  {from:1,to:9,reasoning:"AI generates analysis junior consultants did. Strategic relationship persists but delivery becomes AI-powered.",actions:{team:["Freeze junior analyst hiring","Upskill mid-level on AI orchestration","Hire 1-2 AI/automation engineers"],gtm:["Rebrand from 'advisory' to 'growth outcomes'","Shift to retainer + performance pricing","Build AI-delivered case studies"],ops:["Build AI delivery pipeline for analysis & research","QA workflow: AI generates → senior reviews","Standardize engagement templates"],finance:["Self-fundable — margin expansion funds transition","30-40% margin improvement in 6 months","No external capital needed"],timeline:{m1_3:"Build AI tools internally, pilot on 2-3 clients",m4_6:"Shift new engagements to retainer, reduce junior hiring",m7_12:"AI delivers 70%+ analytical work, humans do judgment"}}},
  {from:1,to:22,reasoning:"Some premium firms lean INTO human as AI commoditizes insight. Human attention becomes luxury.",actions:{team:["Retain only senior-most talent","Reduce team, increase per-person comp","Invest in thought leadership"],gtm:["Increase pricing 2-3x","Rebrand around exclusivity","Target C-suite only"],ops:["Limit AI in client-facing work","Use AI internally for prep only","Create premium experience rituals"],finance:["Higher margins, lower volume","No fundraising — premium lifestyle business","Expect revenue dip then recovery"],timeline:{m1_3:"Identify top 20% clients, reshape offering",m4_6:"Shed lower-tier clients, rebrand, increase prices",m7_12:"Premium boutique with 3-5x margins on fewer engagements"}}},
  {from:2,to:10,reasoning:"BPO's value was cheap labor. AI is cheaper. Survivors become AI-first ops agencies.",actions:{team:["Plan downsizing of ops staff (30-50% over 12mo)","Retrain top performers as AI supervisors","Hire AI engineers and automation specialists"],gtm:["Shift from 'cheap labor' to 'reliable outcomes'","Move to per-outcome pricing","Target clients frustrated with BPO quality"],ops:["Deploy AI agents for highest-volume tasks first","Build exception routing for edge cases","Implement quality monitoring dashboards"],finance:["Significant upfront AI investment","Plan for revenue dip during transition","Consider raising $2-5M to bridge"],timeline:{m1_3:"Identify top 3 processes, build AI replacement",m4_6:"Migrate first wave, begin staff restructuring",m7_12:"50%+ automated, new pricing on all new contracts"}}},
  {from:3,to:5,reasoning:"Defensive. Every horizontal SaaS bolts on AI. Table stakes, not transformation.",actions:{team:["Hire ML/AI product engineers","Upskill product team on AI patterns","No major restructuring"],gtm:["Add 'AI-powered' messaging","Launch AI as premium upsell","Position against laggard competitors"],ops:["Integrate LLM APIs into product","Build feedback loops for improvement","Ensure AI doesn't break core reliability"],finance:["Fundable from existing revenue","Expected move — not a new raise","Modest churn reduction and upsell"],timeline:{m1_3:"Ship first AI features",m4_6:"Expand AI, launch premium tier",m7_12:"AI features generating upsell, parity achieved"}}},
  {from:3,to:24,reasoning:"Horizontal loses to vertical. Survivors go deep into industries.",actions:{team:["Hire domain experts from target vertical","Replace generalist PMs with vertical specialists","Build industry-credible customer success"],gtm:["Pick ONE vertical, go all-in","Rebrand for vertical","Attend industry events, not tech events"],ops:["Fork product for vertical workflows","Build industry-standard integrations","Vertical-specific onboarding"],finance:["Significant investment — new product essentially","May require $5-15M raise","18-24 month payoff"],timeline:{m1_3:"Select vertical, hire domain experts, research",m4_6:"Build vertical features, 5-10 design partners",m7_12:"Launch vertical product, industry GTM"}}},
  {from:4,to:11,reasoning:"Dev shops adopt AI coding tools. 3x faster. Obvious but temporary advantage.",actions:{team:["Train all devs on Cursor/Copilot/Claude","Freeze junior dev hiring","Upskill PMs on AI-assisted scoping"],gtm:["Market speed: 'weeks not months'","Consider fixed-price over T&M","Fast-turnaround case studies"],ops:["Standardize AI dev workflow","Build AI code review tooling","Reusable AI-generated component libraries"],finance:["No capital needed — immediate margin expansion","Reinvest into productization","40-60% efficiency improvement"],timeline:{m1_3:"All devs using AI daily, first accelerated projects",m4_6:"New pricing, internal tooling maturing",m7_12:"3x speed, but plan next move — competitors catching up"}}},
  {from:5,to:13,reasoning:"AI-augmented SaaS evolves to doing the work. 'Help me write' → 'write and publish for me.'",actions:{team:["Shift from UI to AI agent pipelines","Hire reliability engineers for AI monitoring","Reduce customer success if truly self-serve"],gtm:["From 'helps you work' to 'does the work'","Outcome-based or usage-based pricing","Target those who outsource to humans"],ops:["Build confidence scoring","Human-in-loop for low-confidence","Outcome measurement and feedback loops"],finance:["Significant R&D in reliability","May require $10-20M raise","Higher ARPU, different sales motion"],timeline:{m1_3:"Identify one workflow to fully automate",m4_6:"Beta, measure quality vs human baseline",m7_12:"Autonomous mode for proven workflows"}}},
  {from:6,to:17,reasoning:"Workflow tools evolve to route problems automatically vs requiring configuration.",actions:{team:["Hire AI orchestration engineers","Add domain experts per problem category","Build partnerships with AI providers"],gtm:["From 'build your workflow' to 'describe your problem'","Per-outcome pricing","Target less technical buyers"],ops:["Build intent classification","Routing logic for problems → capabilities","QA across diverse output types"],finance:["Major platform rebuild — $5-15M raise","Network effects create defensibility","Longer to revenue but stronger moat"],timeline:{m1_3:"Intent classification for top 5 use cases",m4_6:"Pilot routing vs self-configured",m7_12:"Expand routing, phase out manual config"}}},
  {from:7,to:10,reasoning:"Vertical consultancies that run the function instead of handing over tools become AI-first ops agencies.",actions:{team:["Retain domain experts, reduce data engineering","Hire AI/ML ops engineers","Shift consultants to ongoing advisors"],gtm:["Stop selling projects, sell managed outcomes","Monthly retainer with outcome SLAs","'We ARE your analytics function'"],ops:["Automate pipeline construction with AI","Build monitoring and alerting","Client dashboards showing continuous value"],finance:["Revenue becomes recurring — huge predictability gain","Self-fundable through retainer conversion","6-month mixed revenue transition"],timeline:{m1_3:"Convert 2-3 best clients to retainer",m4_6:"Standardize managed service, sunset projects",m7_12:"Fully recurring, AI handles 60%+ routine work"}}},
  {from:8,to:12,reasoning:"Horizontal AI implementers die or specialize. Survivors pick a vertical and productize.",actions:{team:["Cut generalist consultants, hire vertical experts","Dedicated product engineering team","Shed non-vertical clients"],gtm:["Pick ONE vertical from past success","Rebrand entirely for vertical","Vertical case studies and thought leadership"],ops:["Productize most-built system","Self-serve onboarding","Monitoring and autonomous capabilities"],finance:["Painful — revenue dips shedding clients","Need $3-8M raise for product build","12-18 months runway for pivot"],timeline:{m1_3:"Analyze past work, select vertical, extract product",m4_6:"MVP, 3-5 design partners",m7_12:"Launch product, shift from services to product revenue"}}},
  {from:9,to:14,reasoning:"Revenue agencies that systematize can migrate to self-serve. Hardest path — revenue is ambiguous.",actions:{team:["Shift from client managers to product engineers","Hire growth data scientists","Gradually reduce account management"],gtm:["Identify ONE most reliable revenue outcome","Build self-serve for that outcome","Performance pricing"],ops:["Instrument every input, output, outcome","Build confidence model for AI autonomy","Progressive: supervised → autonomous"],finance:["High-risk, high-reward","Likely $10-25M venture funding","12-18mo revenue model transition"],timeline:{m1_3:"Instrument delivery, find most automatable loop",m4_6:"Self-serve prototype, test on simplest segment",m7_12:"Limited self-serve alongside agency"}}},
  {from:10,to:13,reasoning:"Efficiency agencies have cleanest automation path. Structured tasks, measurable outcomes.",actions:{team:["Progressive ops staff reduction","Humans: doer → exception handler → monitor","Hire product/platform engineers"],gtm:["Self-serve tier alongside managed service","Managed = premium for complex clients","From 'our team' to 'our platform'"],ops:["Confidence scoring per task type","Automated exception routing","Outcome dashboards replace status updates"],finance:["Self-fundable if margins healthy","Self-serve has much lower COGS","12-month parallel operation"],timeline:{m1_3:"Top 3 automatable tasks → fully autonomous",m4_6:"Self-serve beta, parallel with managed",m7_12:"Self-serve majority, managed for enterprise"}}},
  {from:11,to:12,reasoning:"Dev shops building the same thing repeatedly should productize instead of rebuilding.",actions:{team:["Project devs → product devs","Hire product manager","Reduce client-facing PMs"],gtm:["Find system built 3+ times","Package as product with self-serve","Subscription not project pricing"],ops:["Extract patterns into product","Multi-tenant from single-tenant","Config layer replacing custom dev"],finance:["Investment while maintaining services","Consider $2-5M seed","12-month dual-track"],timeline:{m1_3:"Audit projects, find pattern, MVP",m4_6:"5 pilot customers, services for revenue",m7_12:"Product recurring revenue, wind down custom"}}},
  {from:12,to:13,reasoning:"Vertical ops expands scope. Partial autonomy → full autonomy.",actions:{team:["Reduce support as automation expands","Invest in reliability engineering","AI safety and rollback capabilities"],gtm:["From 'X tasks' to 'all ops in domain'","Outcome-based pricing with SLAs","Target larger customers"],ops:["Expand autonomous coverage progressively","Comprehensive monitoring and alerting","Automatic rollback for failures"],finance:["Scale economics improve dramatically","Series A/B ($10-30M) to capture market","Approaching SaaS-like margins"],timeline:{m1_3:"Expand from core to adjacent tasks",m4_6:"90%+ automation, SLA-backed pricing",m7_12:"Full autonomous, human for novel edge cases only"}}},
  {from:13,to:15,reasoning:"Service-as-software accumulates context. Enough context enables personalization and expansion.",actions:{team:["Hire context/personalization engineers","Data science for customer understanding","Reduce support as personalization works"],gtm:["Single outcome → personalized multi-outcome","Price on value, not tasks","'Your AI [function] that knows your business'"],ops:["Customer context models from usage data","Adaptive delivery learning each customer","Expand outcomes based on context"],finance:["Significant R&D in personalization","Venture-scale: $20-50M+","Winner-take-most dynamics"],timeline:{m1_3:"Build context models from usage data",m4_6:"Personalized delivery for top customers",m7_12:"Expand across base, add outcome types"}}},
  {from:14,to:15,reasoning:"Same as efficiency but harder. Revenue SaaS needs deep context to work.",actions:{team:["Heavy domain expert investment","Feedback loop engineering team","Data scientists for attribution"],gtm:["Prove attribution rigorously first","Start where context is deepest","Outcome-only pricing — skin in game"],ops:["Attribution models: actions → revenue","Context ingestion from full revenue stack","Long-feedback-loop monitoring"],finance:["Highest risk, highest reward","Patient capital: $20M+ long horizon","Break-even at 24-36 months"],timeline:{m1_3:"Prove attribution model for core case",m4_6:"Expand context, begin personalization",m7_12:"Personalized revenue outcomes at scale"}}},
  {from:18,to:15,reasoning:"Guilds accumulate collective intelligence. Shared context evolves toward contextual engine.",actions:{team:["Guild governance for data sharing","Shared AI engineering team","Recruit members for coverage"],gtm:["From 'expert network' to 'collective intelligence'","Outcome pricing as AI handles more","Market collective data advantage"],ops:["Shared context from all engagements","AI trained on collective expertise","Standardize quality across guild"],finance:["Cooperative: members fund shared infra","May raise $5-15M for platform","Revenue sharing model"],timeline:{m1_3:"Data sharing standards, shared platform MVP",m4_6:"AI capabilities from collective data",m7_12:"AI handles routine, members do high-judgment"}}},
  {from:20,to:15,reasoning:"BU-aaS accumulates operational context. That context fuels personalization.",actions:{team:["Generalists → vertical specialists + AI eng","Automation reduces headcount per client","Product team for personalization"],gtm:["From 'run function' to 'optimize intelligently'","Add strategic recommendations","Price on business impact"],ops:["Cross-client learning patterns","Predictive models for outcomes","Automate routine, elevate humans"],finance:["Venture-scale: $15-30M","Network effects from cross-client learning","Margins improve with automation"],timeline:{m1_3:"Context models from operational data",m4_6:"Predictive features alongside reactive ops",m7_12:"Personalized, proactive function management"}}},
  {from:23,to:13,reasoning:"Guided self-service dies when AI does the work itself. The guide becomes unnecessary.",actions:{team:["UX designers → AI engineers","Reduce support as AI handles tasks","Domain experts for output validation"],gtm:["From 'help you do it' to 'do it for you'","No more 200 questions","Outcome pricing, not subscription"],ops:["Replace decision trees with AI context ingestion","Document/data ingestion replaces manual input","Confidence scoring for edge cases"],finance:["Existential — someone else kills you if you don't","$10-20M raise likely","Complete revenue model change"],timeline:{m1_3:"AI handles simplest cases end-to-end",m4_6:"AI-first alongside guided flow, A/B test",m7_12:"AI 60%+ autonomous, guided as fallback"}}},
  {from:24,to:13,reasoning:"Vertical SaaS evolves to do the work. Domain knowledge enables outcome delivery.",actions:{team:["AI/ML engineers with domain expertise","Product: feature-building → outcome-building","CS around outcomes, not adoption"],gtm:["From 'manage ops' to 'run your ops'","Outcome-based pricing tier","Target adoption-struggling customers"],ops:["Automate top struggled workflow fully","AI agents within platform","Outcome measurement and QA"],finance:["Self-fund from SaaS revenue","Outcome tier at 3-5x ARPU","Growth round $10-20M to accelerate"],timeline:{m1_3:"Highest-value automation target",m4_6:"'Done for you' tier, pilot with 10",m7_12:"Outcome tier drives new revenue"}}},
  {from:24,to:14,reasoning:"Vertical SaaS with revenue features → revenue outcome delivery. Domain constrains the problem.",actions:{team:["Revenue domain experts for vertical","Attribution engineering team","AI agents for revenue workflows"],gtm:["'We grow your [industry] revenue'","Price on revenue generated","Start most measurable workflow"],ops:["Attribution: actions → revenue outcomes","AI agents execute revenue workflows","Long-term outcome tracking"],finance:["High investment, high payoff","Venture raise $10-20M","Shift to performance-based"],timeline:{m1_3:"Most attributable workflow, build autonomous",m4_6:"Pilot 5-10 customers, prove attribution",m7_12:"Performance-priced tier, scale proven workflows"}}},
  {from:25,to:15,reasoning:"Platforms own operational data. Outcome delivery with that context = contextual engine.",actions:{team:["AI product team for merchant intelligence","Domain experts for outcomes","Platform eng → AI orchestration"],gtm:["From 'build on us' to 'we grow your business'","AI services as premium tier","Outcome-based pricing"],ops:["Context models from platform data","AI agents acting on customer's behalf","Progressive autonomy: suggest → approve → auto"],finance:["Venture-scale endgame: $50M+ rounds","Platform fees → outcome-based revenue","Massive TAM expansion"],timeline:{m1_3:"AI suggestions from data patterns",m4_6:"AI actions with approval (semi-autonomous)",m7_12:"Fully autonomous for proven use cases"}}},
  {from:26,to:16,reasoning:"Data providers evolve from static access to dynamic, continuously maintained context fabric.",actions:{team:["AI engineers for contextual modeling","Real-time data integration team","Data analysts → context engineers"],gtm:["From 'access data' to 'maintain your context'","Price on freshness and integration depth","Target those drowning in fragmented info"],ops:["Real-time integration with customer systems","Adaptive models learning decision patterns","Proactive alerting — push, don't wait"],finance:["Self-fundable from subscriptions","Context broker at 2-3x current pricing","May raise $10-20M to accelerate"],timeline:{m1_3:"Real-time integration prototype, 3-5 customers",m4_6:"Proactive intelligence, test new pricing",m7_12:"Full context broker for early adopters"}}},
  {from:27,to:19,reasoning:"API providers commoditizing evolve into embedded intelligence inside other products.",actions:{team:["Partnerships/BD team","Integration engineers for embedding","General API → vertical fine-tuning"],gtm:["From 'use our API' to 'we power your AI'","Price on value through partners","Target platforms needing AI outcomes"],ops:["White-label deployment infra","Partner-specific fine-tuning","SLAs and monitoring for embedded"],finance:["High-volume, lower-margin","Venture-scale in major platforms: $20M+","Revenue tied to partner growth"],timeline:{m1_3:"2-3 embedded partnerships, framework",m4_6:"Scale deployments, partner metrics",m7_12:"Embedded revenue ≥ direct API revenue"}}}
];

// 7 founder profiles
const PROFILES = [
  {id:"consultancy",label:"Consultancy / Agency",icon:"\u{1F9D1}\u200D\u{1F4BC}",cur:[1,7,8],tgt:[9,10,18,20,22],advice:"Your relationships and domain knowledge are your moat — but delivery is being commoditized. Keep the human interface for trust, replace delivery with AI. Stop selling hours, start selling outcomes."},
  {id:"devshop",label:"Dev / Software Shop",icon:"\u{1F4BB}",cur:[4,11],tgt:[12,20,17],advice:"Building software is commoditizing fastest. Specialize in a vertical and productize, or stop building tools and operate the outcomes. 'Build and handover' has ~18 months."},
  {id:"saas",label:"SaaS Product",icon:"\u{1F4E6}",cur:[3,5,6,24],tgt:[13,14,15,12],advice:"Your customers accepted your tool because custom was too expensive. AI changes that. Evolve from 'here's a tool' to 'here's the outcome.' Your data and domain logic are your head start."},
  {id:"data",label:"Data / Analytics Co",icon:"\u{1F4CA}",cur:[7,26],tgt:[16,15,20],advice:"You're sitting on the most valuable AI-era asset: context. Evolve from selling data access to maintaining a living orientation fabric."},
  {id:"platform",label:"Platform / Marketplace",icon:"\u{1F3D7}\uFE0F",cur:[25,23],tgt:[15,17],advice:"You own the customer's operational data. Use it to progressively do what they do manually. Every config/interpret step is an AI outcome opportunity."},
  {id:"starting",label:"Starting from Scratch",icon:"\u{1F680}",cur:[],tgt:[9,10,12,20,16],advice:"No legacy — that's your advantage. Start delivering outcomes via human interface (agency), acquire context each engagement, then automate. Services wedge = revenue + context + product insight."},
  {id:"freelancer",label:"Freelancer / Solo",icon:"\u{1F3AF}",cur:[1,4],tgt:[18,22,9],advice:"Your expertise doesn't scale. Three paths: guild (share AI infra), premium-artisanal (charge more for human), or AI-first agency (agency outcomes solo)."}
];

// Lookup tables
const STATUS_CONFIG = {
  legacy:   {c:"#ef4444", bg:"#fef2f2", l:"Legacy"},
  current:  {c:"#f59e0b", bg:"#fffbeb", l:"Current"},
  emerging: {c:"#22c55e", bg:"#f0fdf4", l:"Emerging"},
  frontier: {c:"#8b5cf6", bg:"#f5f3ff", l:"Frontier"}
};

const INTERFACE_ICONS = {human:"\u{1F9D1}",gui:"\u{1F5A5}\uFE0F",hybrid:"\u{1F500}",none:"\u{1F47B}"};

const PRICING_LABELS = {project:"Project",retainer:"Retainer",subscription:"Subscription",outcome:"Outcome-based"};

const PROBLEM_COLORS = {revenue:"#3b82f6",efficiency:"#10b981",capability:"#f59e0b"};

const ACTION_ICONS = {team:"\u{1F465}",gtm:"\u{1F4E3}",ops:"\u2699\uFE0F",finance:"\u{1F4B0}"};

const ACTION_LABELS = {team:"Team",gtm:"Go-to-Market",ops:"Operations",finance:"Finance"};

const TIMELINE_LABELS = {m1_3:"Months 1-3",m4_6:"Months 4-6",m7_12:"Months 7-12"};
